config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'registrations' }
  resources :sittings
  resources :users
  get 'my-sittings', :to => 'sittings#my_sittings'

  root 'home#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/sitting.rb
class Sitting < ApplicationRecord
  belongs_to :parent, class_name: 'User'
  # belongs_to :nanny, class_name: 'User'
end

app/models/user.rb
class User < ApplicationRecord
  has_many :sittings
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  protect_from_forgery with: :exception

  def index
    
  end

end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

 private

 def sign_up_params
   params.require(:user).permit(:last_name, :first_name, :email, :password, :password_confirmation)
 end

 def account_update_params
   params.require(:user).permit(:last_name, :first_name, :email, :password, :password_confirmation, :current_password)
 end
end

app/controllers/sittings_controller.rb
class SittingsController < ApplicationController
  before_action :set_sitting, only: [:show, :edit, :update, :destroy]

  
  def index
    @sittings = Sitting.all
  end

  def my_sittings
    @my_sittings = Sitting.where(parent_id: current_user.id) 
  end
  
  def show
  end

  def new
    @sitting = Sitting.new
  end

  
  def edit
  end

   
  def create
    @sitting = Sitting.new(sitting_params)
    respond_to do |format|
      if @sitting.start_time > @sitting.stop_time
        format.html { redirect_to new_sitting_path, notice: "Sorry. Stop Time can't be before Start Time!" }
        
      elsif @sitting.save
        format.html { redirect_to @sitting, notice: 'Sitting was successfully created.' }
        format.json { render :show, status: :created, location: @sitting }
      else
        format.html { render :new }
        format.json { render json: @sitting.errors, status: :unprocessable_entity }
      end
    end
  end

  
  def update
    respond_to do |format|
      if @sitting.parent_id != current_user.id
       format.html { redirect_to @sitting, notice: 'Sorry, you may only edit your own sittings!' }
      elsif @sitting.update(sitting_params)
        format.html { redirect_to @sitting, notice: 'Sitting was successfully updated.' }
        format.json { render :show, status: :ok, location: @sitting }
      else
        format.html { render :edit }
        format.json { render json: @sitting.errors, status: :unprocessable_entity }
      end
    end
  end

  
  def destroy
    @sitting.destroy
    respond_to do |format|
      format.html { redirect_to sittings_url, notice: 'Sitting was successfully deleted.' }
      format.json { head :no_content }
    end
  end

  private
    def set_sitting
      @sitting = Sitting.find(params[:id])
    end

    def sitting_params
      whitelisted = params.require(:sitting).permit(:start_time, :stop_time, :duration, :number_of_kids, :billed_amount)
      whitelisted.merge(parent_id: current_user.id.to_i)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

 
  def index
    @users = User.all
  end

  
  def show
  end

  
  def new
    @user = User.new
  end

  
  def edit
  end

  
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to root_path, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def set_user
      @user = User.find(params[:id])
    end

    def user_params
      params.require(:user).permit(:last_name, :first_name, :rating, :age, :gender, :hourly_rate, :add_child_rate)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sittings_helper.rb
module SittingsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/home/index.html.erb
<h1 class="text-center" style="color:#6396e8; font-family:Ubuntu;"><em>ZipNanny</em></h1>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title class="text-center" style="color:#6396e8; font-family:Ubuntu;">
    <link href="https://fonts.googleapis.com/css?family=Ubuntu" rel="stylesheet">ZipNanny</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://fonts.googleapis.com/css?family=Ubuntu" rel="stylesheet">
  </head>
  <body>
    
    <nav style="color:#6396e8; padding-top: 20px; padding-left: 10px" class="navbar navbar-toggleable-md navbar-mike bg-primary" >
      <% if current_user %>
      
      <p  style="font-family:Ubuntu; font-size: 250%">ZipNanny</p>
      <div align="right" style="padding-right: 10px">
        <p>Hello, <%= current_user.first_name %>!
          <%= link_to 'All Sittings', sittings_path, {style: "color: #6396e8"} %>
          <%= link_to 'My Sittings', my_sittings_path, {style: "color: #6396e8"} %>
          <%= link_to 'My Profile', user_path(current_user), {style: "color: #6396e8"} %>
          <%= link_to 'Logout', destroy_user_session_path, method: :delete %>
        </div>
        <% else %>
        <p  style="font-family:Ubuntu; font-size: 250%">ZipNanny</p>  
        <div align="right">
          <%= link_to 'Register', new_user_registration_path, {style: "color: #6396e8"} %>
          <%= link_to 'Login', new_user_session_path, {style: "color: #6396e8"} %>
        </div>
        <% end %>
      </nav>
      <%= yield %>
  </body>
</html>ß

app/views/sittings/_form.html.erb
<%= form_for(sitting) do |f| %>
  <% if sitting.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(sitting.errors.count, "error") %> prohibited this sitting from being saved:</h2>

      <ul>
      <% sitting.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  
  <div class="field">
    <%= f.label :date %>
    <%= f.date_select :date %>
  </div>

  <div class="field">
    <%= f.label :start_time %>
    <%= f.time_select :start_time %>
  </div>

  <div class="field">
    <%= f.label :stop_time %>
    <%= f.time_select :stop_time %>
  </div>


  <div class="field">
    <%= f.label :number_of_kids %>
    <%= f.number_field :number_of_kids %>
  </div>

  <!-- <div class="field">
    <%= f.label :billed_amount %>
    <%= f.number_field :billed_amount %>
  </div> -->

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/sittings/_new_form.html.erb
<head><link href="https://fonts.googleapis.com/css?family=Ubuntu" rel="stylesheet"></head>
<div class="text-center">
<%= form_for(sitting) do |f| %>
  <% if sitting.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(sitting.errors.count, "error") %> prohibited this sitting from being saved:</h2>

      <ul>
      <% sitting.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


  <div class="field" style="color:#6396e8">
    <%= f.label :start_time %>
    <%= f.datetime_select :start_time, ampm: true, minute_step: 15 %>
  </div>

  <div class="field" style="color:#6396e8">
    <%= f.label :stop_time %>
    <%= f.datetime_select :stop_time ,ampm: true, minute_step: 15 %>
  </div>


  <div class="field" style="color:#6396e8">
    <%= f.label :number_of_kids %>
    <%= f.number_field :number_of_kids %>
  </div>

  <!-- <div class="field">
    <%= f.label :billed_amount %>
    <%= f.number_field :billed_amount %>
  </div> 

  <div class="field">
    <%= f.label :nanny_id %>
    <%= f.number_field :nanny_id %>
  </div>  -->


  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>
</div>

app/views/sittings/edit.html.erb
<head><link href="https://fonts.googleapis.com/css?family=Ubuntu" rel="stylesheet"></head>
<h1 class="text-center" style="color:#6396e8; font-family:Ubuntu;">Editing Sitting</h1>

<%= render 'form', sitting: @sitting %>
<div class="text-center">
<%= link_to 'Show', @sitting, {style: "color: #6396e8"} %> |
<%= link_to 'Back', sittings_path, {style: "color: #6396e8"} %>
</div>

app/views/sittings/index.html.erb
<head><link href="https://fonts.googleapis.com/css?family=Ubuntu" rel="stylesheet"></head>

<p id="notice"><%= notice %></p>

<h1 class="text-center" style="color:#6396e8" font-family:Ubuntu;"><em>All Sittings</em></h1>

<div class="text-center">
<table align="center" style="width:80%">
  <thead>
    <tr style="color:#6396e8" >
      
      <th>Start Time</th>
      <th>Stop Time</th>
      <th>Duration</th>
      <th>Number Of Kids</th>
      <th>Billed Amount</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @sittings.each do |sitting| %>
      <tr style="color:#6396e8">
        
        <td><%= sitting.start_time %></td>
        <td><%= sitting.stop_time %></td>
        <td><%= (sitting.stop_time - sitting.start_time)/3600 %></td>
        <td><%= sitting.number_of_kids %></td>
        <td><%= ((sitting.stop_time - sitting.start_time)/3600)*(sitting.number_of_kids)*10 %></td>
        <td><%= link_to 'Sitting Details', sitting, {style: "color: #6396e8"} %></td>
        <td><%= link_to 'Edit Sitting', edit_sitting_path(sitting), {style: "color: #6396e8"} %></td>
        <!-- <td><%= link_to 'Delete Sitting', sitting, method: :delete, data: { confirm: 'Are you sure?' } %></td> -->
      </tr>
    <% end %>
  </tbody>
</table>

<br>


<h3><%= link_to 'New Sitting', new_sitting_path, {style: "color: #6396e8"} %></h3>



</div>

app/views/sittings/my_sittings.html.erb
<head><link href="https://fonts.googleapis.com/css?family=Ubuntu" rel="stylesheet"></head>

<p align="center" id="notice"><%= notice %></p>

<h1 class="text-center" style="color:#6396e8; font-family:Ubuntu;">My Sittings</h1>


<div class="text-center">
<table align="center" style="color:#6396e8; width:80%">
  <thead>
    <tr>
      
      <th>Start Time</th>
      <th>Stop Time</th>
      <th>Duration</th>
      <th>Number Of Kids</th>
      <th>Billed Amount</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @my_sittings.each do |my_sitting| %>
      <tr>
        <td><%= my_sitting.start_time %></td>
        <td><%= my_sitting.stop_time %></td>
        <td><%= (my_sitting.stop_time - my_sitting.start_time)/3600 %></td>
        <td><%= my_sitting.number_of_kids %></td>
        <td><%=  ((my_sitting.stop_time - my_sitting.start_time)/3600) * my_sitting.number_of_kids * 10 %></td>
        <td><%= link_to 'Sitting Details', my_sitting, {style: "color: #6396e8"} %></td>
        <td><%= link_to 'Edit Sitting', edit_sitting_path(my_sitting), {style: "color: #6396e8"} %></td>
        <!-- <td><%= link_to 'Delete Sitting', my_sitting, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr> -->
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Sitting', new_sitting_path, {style: "color: #6396e8"} %>

</div>

app/views/sittings/new.html.erb
<head><link href="https://fonts.googleapis.com/css?family=Ubuntu" rel="stylesheet"></head>
<p align="center" style="color: #fff426" id="notice"><%= notice %></p>
<h1 class="text-center" style="color:#6396e8; font-family:Ubuntu;">New Sitting</h1>

<%= render 'new_form', sitting: @sitting %>
<div class="text-center" style="color:#6396e8">
<%= link_to 'Back', sittings_path, {style: "color: #6396e8"} %>
</div>

app/views/sittings/show.html.erb
<head><link href="https://fonts.googleapis.com/css?family=Ubuntu" rel="stylesheet"></head>

<p id="notice"><%= notice %></p>

<h1 class="text-center" style="color:#6396e8; font-family:Ubuntu;">My Sitting</h1>
<div class="text-center" style="color:#6396e8;">
<p>
  <strong>Assigned Nanny:</strong>
  <%= @sitting.nanny_id %>
</p>

<p>
  <strong>Start Time:</strong>
  <%= @sitting.start_time %>
</p>

<p>
  <strong>Stop Time:</strong>
  <%= @sitting.stop_time %>
</p>

<p>
  <strong>Duration</strong>
  <%=(@sitting.stop_time - @sitting.start_time)/3600%>
</p>


<p>
  <strong>Number Of Kids:</strong>
  <%= @sitting.number_of_kids %>
</p>

<p>
  <strong>Billed Amount:</strong>
  <%= ((@sitting.stop_time - @sitting.start_time)/3600)*(@sitting.number_of_kids)*10 %>
</p>

<%= link_to 'Edit', edit_sitting_path(@sitting), {style: "color: #6396e8"} %> |
<%= link_to 'Back', sittings_path, {style: "color: #6396e8"} %>
</div>

app/views/users/_form.html.erb
<%= form_for(user) do |f| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


  <div class="field">
    <%= f.label :first_name %>
    <%= f.text_field :first_name %>
  </div>

  <div class="field">
    <%= f.label :last_name %>
    <%= f.text_field :last_name %>
  </div>
  
  

  <div class="field">
    <%= f.label :age %>
    <%= f.number_field :age %>
  </div>

  <div class="field">
    <%= f.label :gender %>
    <%= f.text_field :gender %>
  </div>

  

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1 align="center" style="color:#6396e8; font-family:Ubuntu">Editing User</h1>

<div align="center" style="color:#6396e8">
<%= render 'form', user: @user %>

<%= link_to 'Show', @user, {style: "color: #6396e8"} %> |
<%= link_to 'Back', users_path, {style: "color: #6396e8"} %>
</div>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1 align="center" style="color:#6396e8; font-family:Ubuntu">Users</h1>

<table align="center" style="color:#6396e8" width= 80%>
  <thead>
    <tr>
      <th>Last name</th>
      <th>First name</th>
      <th>Rating</th>
      <th>Age</th>
      <th>Gender</th>
      
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.last_name %></td>
        <td><%= user.first_name %></td>
        <td><%= user.rating %></td>
        <td><%= user.age %></td>
        <td><%= user.gender %></td>
        <td><%= link_to 'View Profile', user_path(current_user), {style: "color: #6396e8"} %>
          
        </td>
        <td><%= link_to 'Edit Profile', edit_user_path(user), {style: "color: #6396e8"} %></td>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/users/new.html.erb
<h1 align="center" style="color:#6396e8; font-family:Ubuntu">New User</h1>
<div align="center" style="color:#6396e8">
<%= render 'form', user: @user %>

<%= link_to 'Back', users_path, {style: "color: #6396e8"} %>
</div>

app/views/users/show.html.erb
<h1 align="center" style="color:#6396e8; font-family:Ubuntu">My Profile</h1>

<p id="notice"><%= notice %></p>
<div align="center" style="color:#6396e8">
<p>
  <strong>Last name:</strong>
  <%= @user.last_name %>
</p>

<p>
  <strong>First name:</strong>
  <%= @user.first_name %>
</p>

<p>
  <strong>Rating:</strong>
  <%= @user.rating %>
</p>

<p>
  <strong>Age:</strong>
  <%= @user.age %>
</p>

<p>
  <strong>Gender:</strong>
  <%= @user.gender %>
</p>



<%= link_to 'Edit', edit_user_path(@user), {style: "color: #6396e8"} %> |
<%= link_to 'Back', users_path, {style: "color: #6396e8"} %>
</div>